version: '3'

services:
  backend:
    build: ./backend
    command: python app.py
    volumes:
      - ./backend:/code
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    command: yarn start
    ports:
      - "3000:3000"
